# Generated by Django 6.0.3 on 2026-04-02 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Planned budget amount', max_digits=10)),
                ('month', models.DateField(help_text='First day of the month for this budget (e.g., 2026-04-01)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='category.category')),
            ],
            options={
                'ordering': ['-month', 'category__name'],
                'unique_together': {('category', 'month')},
            },
        ),
    ]
