# Generated by Django 6.0.3 on 2026-03-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='import_hash',
            field=models.CharField(blank=True, help_text='Hash to prevent duplicate imports', max_length=255, null=True, unique=True),
        ),
    ]
