# Generated by Django 6.0.3 on 2026-03-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='card_suffix',
            field=models.CharField(blank=True, help_text='Last 4 digits or suffix to auto-match on imports', max_length=10, null=True),
        ),
    ]
